### ISSUE TITLE
The forgot password link doesn't redirect to the right route.

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#122]
The forgot password link doesn't redirect to the right route.
<img width="1267" alt="screen shot 2015-11-17 at 11 42 59 am" src="https://cloud.githubusercontent.com/assets/2946769/11209904/623b8f4c-8d35-11e5-9ad1-945dbef73970.png">

**Comment by sirolad** [comment]
This issue has been fixed.
