### ISSUE TITLE
Pibbble link doesn't redirect to the correct route

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#124]
<img width="1272" alt="screen shot 2015-11-17 at 11 39 20 am" src="https://cloud.githubusercontent.com/assets/2946769/11209960/aec49a34-8d35-11e5-911d-6a6f8a3a9208.png">

**Comment by sirolad** [comment]
This issue has been fixed.

**Comment by unicodeveloper** [comment]
When was it fixed?
