### ISSUE TITLE
Please remove the sections for teams and miscellaneous, they are not needed at this stage

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#125]
<img width="1272" alt="screen shot 2015-11-17 at 11 39 20 am" src="https://cloud.githubusercontent.com/assets/2946769/11209986/e1cc31b2-8d35-11e5-9a66-4e125b177bbf.png">

**Comment by sirolad** [comment]
While the teams section might not be needed now,  a good number of things are very useful in the miscellaneous section.

**Comment by unicodeveloper** [comment]
Yeah..that's true
