### ISSUE TITLE
The Description field is too small for uploading projects.

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#127]
You can change that to be a textarea, so that the user can have a lot more space for the description of the project 
<img width="1268" alt="screen shot 2015-11-17 at 2 43 52 pm" src="https://cloud.githubusercontent.com/assets/2946769/11210522/c77e3af4-8d39-11e5-89ec-86c0616127bb.png">

**Comment by sirolad** [comment]
This issue has been resolved.
