### ISSUE TITLE
Every project has a default large text attached to it, something that the user didn't write.

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#128]
``` text
Music and event concept I am currently working on. Locate artists in your city, listen and purchase their music. Attend and buy tickets for events. Connected to the most common music streaming services and Resident Advisor for the events.

Hope you like it and feel ready for the weekend! Press "L" on your keyboard if you do, and follow me to catch my upcoming work.
```

That block of text above is on every project. Why?..I added a new project and I didn't add that text. Please fix, that text shouldn't be added on the creation of new projects.
<img width="1194" alt="screen shot 2015-11-17 at 2 58 22 pm" src="https://cloud.githubusercontent.com/assets/2946769/11210793/b723b93e-8d3b-11e5-84b7-3f27aee3f5e6.png">

**Comment by sirolad** [comment]
This issue has been resolved.
