### ISSUE TITLE
Hire me should be personalised

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#136]
1. A lot users don't like their email just publicly shown. Please make the email invisible, don't show anyone's email.
2. Also remove the cc: and send me a copy of this email. it's not necessary.
3. When I am checking my profile, I don't want to be able to email myself. I should only see something like "I am available for hire" in the dialog box. Use Laravel's ACL( Access and Control Logic) feature for that. It involves creating [Policies](https://mattstauffer.co/blog/acl-access-control-list-authorization-in-laravel-5-1#policies). 

Contact unicodeveloper About Work should be "Contact unicodeveloper about work"

<img width="1118" alt="screen shot 2015-11-22 at 1 13 37 pm" src="https://cloud.githubusercontent.com/assets/2946769/11323140/55740c50-911b-11e5-9ff4-88da789bdfe5.png">

**Comment by sirolad** [comment]
This issue has been resolved.

Best Regards,

_Surajudeen Akande_
Software Developer, _Andela_
+2348037690966 | Skype: sirolad https://webapp.wisestamp.com/#
http://facebook.com/runthinz  http://twitter.com/babatoclean1
http://github.com/andela-sakande

**Comment by unicodeveloper** [comment]
Where is the PR for it?
