### ISSUE TITLE
Skills dialog box shows white blank page if the user hasn't updated his/her skills column

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#188]
Don't you think there should be a default text that says something like `No Updated Skills yet` or something very appropriate until the user has that part of his/her bio updated?

<img width="1086" alt="screen shot 2015-12-07 at 4 13 41 pm" src="https://cloud.githubusercontent.com/assets/2946769/11627686/a5dd8f0c-9cfd-11e5-8958-8f1dcae4563d.png">

**Comment by sirolad** [comment]
This issue has been resolved.
