### ISSUE TITLE
Images of various projects do not show any longer

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#202]
Do we have issues with cloudinary?... The images on our platform do not show again?
<img width="1118" alt="screen shot 2015-12-14 at 12 26 45 pm" src="https://cloud.githubusercontent.com/assets/2946769/11779888/3d4260c4-a25e-11e5-972f-d5b2c0dbbd9e.png">

**Comment by unicodeveloper** [comment]
@andela-oogunjimi Your PR made this happen, please check and fix!

**Comment by andela-oogunjimi** [comment]
It'll be fixed today.
