### ISSUE TITLE
When I try to create a new project, this is the error I get

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#211]
<img width="1115" alt="screen shot 2015-12-15 at 4 23 31 am" src="https://cloud.githubusercontent.com/assets/2946769/11801177/cec05b8e-a2e3-11e5-8ea5-c13c2ffbdbad.png">

**Comment by andela-oogunjimi** [comment]
I'll send a PR fix soon. 
I guess it has to do with column names.
A particular column name in our code and migrations is _imageUrl_ while in our database this column name is _imageurl_.

**Comment by andela-oogunjimi** [comment]
The issue has been resolved for a while now. Actually since Wednesday this week.
Although I still noticed some hours ago that we couldn't create new projects.
This is obviously not because of any functionality or feature I added.
