### ISSUE TITLE
The Check Url button doesn't do anything, what's its purpose?

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#212]
<img width="1024" alt="screen shot 2015-12-15 at 4 26 16 am" src="https://cloud.githubusercontent.com/assets/2946769/11801205/07e303e4-a2e4-11e5-89b7-eac214d45238.png">

**Comment by andela-oogunjimi** [comment]
Check Url verifies that we don't have the provided project URL in the database.

**Comment by andela-oogunjimi** [comment]
The issue has been resolved for a while now. Actually since Wednesday this week.
