### ISSUE TITLE
The appropriate url should be /dashboard  not /projects 

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#257]
Right now, when you click on the dropdown to go to the dashboard, the url for the dashboard is `https://pibbble-staging.herokuapp.com/projects` . It should be `https://pibbble-staging.herokuapp.com/dashboard`

<img width="1109" alt="screen shot 2016-01-07 at 5 29 25 pm" src="https://cloud.githubusercontent.com/assets/2946769/12176031/b336aed8-b565-11e5-8fe3-cfe7175d5ca5.png">

**Comment by unicodeveloper** [comment]
I see that you have added the route, but you havent made the change in the drop down menu. When I click it still redirects me to `/projects`

**Comment by gngchrs** [comment]
@unicodeveloper this was merged in #269 , I'm not sure why it's not in the staging though!
