### ISSUE TITLE
The github, facebook and linkedIn links don't redirect to anywhere even when I have values updated for those fields in the my profile settings

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#259]
All the links should also open on a new tab when clicked.

<img width="989" alt="screen shot 2016-01-07 at 5 28 29 pm" src="https://cloud.githubusercontent.com/assets/2946769/12176150/4e3cca02-b566-11e5-89ba-73b4e076f6ef.png">

**Comment by gngchrs** [comment]
@unicodeveloper I think I've only enabled the Urls, I'm wondering if the links should not appear at all in the dashboard if a user has not set them?

**Comment by unicodeveloper** [comment]
@andela-cganga that makes sense. Let's do it that way, the links and social media icons should not appear if  a user has not set them in the profile settings.

Please, send a new PR for that

**Comment by gngchrs** [comment]
Ok. @unicodeveloper so I won't mark it on Pivotal as finished yet

**Comment by unicodeveloper** [comment]
@andela-cganga Please I need the links to be opened up on another tab when clicked

**Comment by gngchrs** [comment]
@unicodeveloper ok. Working on it
