### ISSUE TITLE
Pagination gets broken whenever the pages are been sorted by likes, views or comment

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#261]
<img width="1116" alt="screen shot 2016-01-07 at 6 06 42 pm" src="https://cloud.githubusercontent.com/assets/2946769/12176810/83b3e69a-b569-11e5-9069-97eaca32b776.png">

<img width="1105" alt="screen shot 2016-01-07 at 6 05 13 pm" src="https://cloud.githubusercontent.com/assets/2946769/12176824/931e6114-b569-11e5-803e-92cdcdc9da5a.png">

**Comment by sirolad** [comment]
This issue has been resolved.

**Comment by unicodeveloper** [comment]
We need to refactor the way you did it, not clean enough

**Comment by sirolad** [comment]
This issue has been resolved
