### ISSUE TITLE
I can't update my first project for some unphantomable reasons

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#263]
When i click on the edit link of the second project, the modal dialog box comes up where i can edit the details of my project.

When i click on the edit link of the first project, nothing happens. Please look into this!

<img width="958" alt="screen shot 2016-01-07 at 6 20 33 pm" src="https://cloud.githubusercontent.com/assets/2946769/12177232/641dda46-b56b-11e5-902f-9ae7fa53b646.png">

**Comment by sirolad** [comment]
I have checked this on about four different computers, and it's working fine, please check again.
