### ISSUE TITLE
You cannot update profile settings with empty parameters

### ISSUE THREAD

**Issue by gngchrs** [andela/pibbble#296]
If you update your settings e.g twitter with empty (to remove the handle), then press update settings, the handle comes back.
![snip20160125_2](https://cloud.githubusercontent.com/assets/3910877/12552079/6fe9ab7a-c380-11e5-8110-5a524adcce78.png)

**Comment by unicodeveloper** [comment]
@andela-cganga Please handle this

**Comment by gngchrs** [comment]
@unicodeveloper Ok. Will work on it.
