### ISSUE TITLE
Implement Creating Meetups Faqs

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#307]
This is Dribbble meetup [faqs](https://dribbble.com/meetups/faq)

<img width="1118" alt="screen shot 2016-01-27 at 4 51 54 am" src="https://cloud.githubusercontent.com/assets/2946769/12603304/c6f94164-c4b1-11e5-9262-fa9abe855c6b.png">

We want Pibbble meetups faqs to be somewhat like this too. So create a route and page for this.

Please sync with @andela-oisola for better understanding of the meetups idea.

**Comment by andela-aonyango** [comment]
This feature has been implemented along with the [Meetups creation feature](https://github.com/andela/pibbble/pull/318) which it was initially supposed to be implemented separately from.
