### ISSUE TITLE
Clicking on a project on the developers list generate errors

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#329]
Was this not the variable you removed the other time we were looking at the contents of project_details.blade.php?

<img width="1119" alt="screen shot 2016-02-22 at 8 29 52 pm" src="https://cloud.githubusercontent.com/assets/2946769/13229909/5a90efde-d9a3-11e5-9623-0c435c867bf7.png">

**Comment by wilmkr** [comment]
I really can't see what is wrong here. I abstracted the variable into a partial and included the partial in the view. I'm still looking at the code closely though to try and ascertain what is wrong...

**Comment by unicodeveloper** [comment]
Please check it out closely, the file might not have properly inherited the variable from the partial

**Comment by wilmkr** [comment]
Ok. I'm pretty sure it's just minor thing...
