### ISSUE TITLE
Following and Followers link are dead

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#330]
Something is broken here. When you click on `Followers` or `Following` Link, nothing happens but this is generated in the console

<img width="1117" alt="screen shot 2016-02-22 at 8 42 19 pm" src="https://cloud.githubusercontent.com/assets/2946769/13230425/97ab52c2-d9a5-11e5-8ca1-4aacff16afb3.png">

@andela-cganga @andela-aonyango Is this as a result of the way you implemented the datepicker functionality?

**Comment by gngchrs** [comment]
@unicodeveloper dipo had moved the scripts to the bottom of the page, I was pairing with @andela-aonyango  and fixed this in the teams PR

**Comment by unicodeveloper** [comment]
Ohh cool, but this was not mentioned in the notes section of the Teams PR
