### ISSUE TITLE
Navdrop down contents doesnt show because the hover is white and the text color on hover is still white

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#73]
<img width="1280" alt="screen shot 2015-10-26 at 7 32 08 am" src="https://cloud.githubusercontent.com/assets/2946769/10722741/b696fb78-7bb3-11e5-9058-a95fd5f0d295.png">

**Comment by unicodeveloper** [comment]
@andela-womokoro when will this be fixed?

**Comment by wilmkr** [comment]
I thought you previously asked ope to fix it. It was he who made it to be
the way it is.

On Mon, Oct 26, 2015 at 11:56 AM, Prosper Otemuyiwa <
notifications@github.com> wrote:

> @andela-womokoro https://github.com/andela-womokoro when will this be
> fixed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/pibbble/issues/73#issuecomment-151099318.

## 

_Wilson Omokoro | Software Developer | Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-803-380-6531 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
Just fix it @andela-womokoro since he didnt

**Comment by wilmkr** [comment]
Ok boss. Am on it.

On Mon, Oct 26, 2015 at 2:31 PM, Prosper Otemuyiwa <notifications@github.com

> wrote:
> 
> Just fix it @andela-womokoro https://github.com/andela-womokoro since
> he didnt
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/pibbble/issues/73#issuecomment-151133890.

## 

_Wilson Omokoro | Software Developer | Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-803-380-6531 | Andela.com http://andela.com/
