### ISSUE TITLE
Social Media authentication using Github or Twitter options

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#74]
Please remove LinkedIn. We really don't need programmers logging in through linkedIn. Github and Twitter is good.

**Comment by unicodeveloper** [comment]
@andela-oogunjimi this feature doesn't work yet. What's the issue?

When I try to login via github, this is what I encounter

<img width="1280" alt="screen shot 2015-11-08 at 6 51 29 am" src="https://cloud.githubusercontent.com/assets/2946769/11019053/f457fa16-85e5-11e5-8b2f-96f4f79950a3.png">

When i try to login via twitter, this is what I encounter

<img width="1280" alt="screen shot 2015-11-08 at 6 57 39 am" src="https://cloud.githubusercontent.com/assets/2946769/11019056/159f49e0-85e6-11e5-850d-1fbdb81b3178.png">

**Comment by andela-oogunjimi** [comment]
It works on my local machine. The branch is avaliable on Github;
feature/social-auth. I believe we have to create another application with
github and twitter. Our applications recognize pibbble as http://pibbble.app.
I'll create applications for https://pibbble-staging.herokuapp.com and also
include some environment variables on heroku. I'll get back to you on these.

Yours sincerely,
Opeyemi Ogunjimi.
_Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
Sure, but the users wouldn't use the app on your local machine, would they?

Have you set the needed environment variables on heroku?...and what do you mean create another application with github and twitter?

`Our applications recognize pibble as http://pibbble.app` . This is very vague, what applications?

**Comment by unicodeveloper** [comment]
I need feedback on this every 30 minutes from now

**Comment by andela-oogunjimi** [comment]
Okay.

On Mon, Nov 9, 2015 at 12:23 PM, Prosper Otemuyiwa <notifications@github.com

> wrote:
> 
> I need feedback on this every 30 minutes from now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/pibbble/issues/74#issuecomment-155032413.

## 

_Opeyemi Ogunjimi | Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/

**Comment by andela-oogunjimi** [comment]
No, users would not use the app on my local machine.
I have set environment variables for GitHub OAuth.
I mean register or create the application on github and twitter. A new one
different from the application used for development.

Yours sincerely,
Opeyemi Ogunjimi.
_Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
Yeah, you should have done that already.

**Comment by andela-oogunjimi** [comment]
Prosper,

I have set the environment variables for Twitter OAuth.

Kind regards,
Opeyemi Ogunjimi.
_Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/

On Mon, Nov 9, 2015 at 1:09 PM, Prosper Otemuyiwa notifications@github.com
wrote:

> Yeah, you should have done that already.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/pibbble/issues/74#issuecomment-155047355.

## 

_Opeyemi Ogunjimi | Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
What about Github?

**Comment by andela-oogunjimi** [comment]
I have done that earlier.

On Mon, Nov 9, 2015 at 1:24 PM, Prosper Otemuyiwa notifications@github.com
wrote:

> What about Github?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/pibbble/issues/74#issuecomment-155050350.

## 

_Opeyemi Ogunjimi | Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
So can a user log in successfully with github and twitter now?

**Comment by andela-oogunjimi** [comment]
No. We have to make some changes to the users table.

On Mon, Nov 9, 2015 at 2:18 PM, Prosper Otemuyiwa notifications@github.com
wrote:

> So can a user log in successfully with github and twitter?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/pibbble/issues/74#issuecomment-155058892.

## 

_Opeyemi Ogunjimi | Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
Make the changes and send in a PR to that effect, the other team members know about this change too?

**Comment by andela-oogunjimi** [comment]
You have merged my PR.

On Mon, Nov 9, 2015 at 3:53 PM, Prosper Otemuyiwa notifications@github.com
wrote:

> Make the changes and send in a PR to that effect, the other team members
> know about this change too?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/pibbble/issues/74#issuecomment-155085002.

## 

_Opeyemi Ogunjimi | Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/
