### ISSUE TITLE
Homepage contents should be fetched from the database

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#75]
What's the status on this @andela-womokoro ?

**Comment by wilmkr** [comment]
I have populated the database with fake data using a faker package. So
currently the values for project titles, likes, and views are being
retrieved from the database.

I'm currently working on the images.

On Mon, Oct 26, 2015 at 7:42 AM, Prosper Otemuyiwa <notifications@github.com

> wrote:
> 
> What's the status on this @andela-womokoro
> https://github.com/andela-womokoro ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/pibbble/issues/75.

## 

_Wilson Omokoro | Software Developer | Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-803-380-6531 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
Coool..please take note that no image should be stored locally, only their urls should be stored. They should be stored in the cloud e.g cloudinary, amazon web service etc
