### ISSUE TITLE
Data missing from the homepage

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#81]
<img width="1280" alt="screen shot 2015-10-26 at 4 46 53 pm" src="https://cloud.githubusercontent.com/assets/2946769/10734072/c4503024-7c01-11e5-8430-27c4ab9be6e7.png">

**Comment by wilmkr** [comment]
Just run the following two commands to seed the users and projects table

```
php artisan db:seed --class=UsersTableSeeder
php artisan db:seed --class=ProjectsTableSeeder
```
