### ISSUE TITLE
I prefer the header to be fixed than the footer

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#84]
The footer is too large, so a user has to really scroll to see several contents. Making the header fixed instead would be better

**Comment by ghost** [comment]
I am working on that now.

_Oladipupo Isola | Software Developer, Andela_
_See what TechCrunch
http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/
and StackOverflow
http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/
say
about us!_
(c) +234-703-302-0216 | Andela.com http://andela.com/

On Mon, Oct 26, 2015 at 5:21 PM, Prosper Otemuyiwa <notifications@github.com

**Comment by unicodeveloper** [comment]
Great
